# VelocityEssentials Configuration

# Database settings
database:
  # SQLite database file will be created in the plugin folder
  # No configuration needed! Just works out of the box.
  type: "sqlite"

# Server memory settings  
server-memory:
  # Enable server memory feature
  enabled: true
  
  # Server to send players to if their last server is unavailable
  fallback-server: "lobby"
  
  # Where to send first-time players
  first-join-server: "lobby"
  
  # How many days to remember player's last server
  remember-days: 30
  
  # Servers that should not be remembered (temp servers, event servers, etc)
  blacklisted-servers:
    - "event"
    - "temp"
  
  # Permission to bypass server memory (always go to fallback)
  bypass-permission: "velocityessentials.bypass"

discord:
  # Enable Discord webhooks
  enabled: false
  
  # Webhook URL from Discord channel settings
  webhook-url: ""
  
  # Custom webhook appearance (leave empty for defaults)
  username: "VelocityEssentials"
  avatar-url: ""
  
  # Show "joined for the first time!" messages
  show-first-time: true
  
  # Which server should trigger first-time announcements
  first-time-server: "lobby"
  
  # ===== CHAT RELAY SETTINGS =====
  # Enable chat relay to Discord
  chat-relay: true
  
  # Use player's Minecraft head as webhook avatar for each chat message
  # If false, uses the main webhook avatar for all messages
  use-player-head-for-chat: true
  
  # Show which server the message is from
  chat-show-server: false
  
  # Format for server prefix (if enabled)
  chat-server-format: "[{server}]"
  
  # Permission-based prefixes for chat
  # Format: "permission.node": "prefix"
  # First matching permission will be used
  # You can use Discord markdown: ** for bold, __ for underline, etc.
  chat-prefixes:
    "group.owner": "**Owner**"
    "group.admin": "**Admin**"
    "group.moderator": "**Mod**"
    "group.helper": "**Helper**"
    "group.vip+": "**VIP+**"
    "group.vip": "**VIP**"
    "group.supporter": "**Supporter**"
    # Add more as needed
    # You can also use specific permissions:
    "velocityessentials.prefix.developer": "**Dev**"
    "velocityessentials.prefix.builder": "**Builder**"
    
  # Alternative format examples:
  # Using emoji:
  # chat-prefixes:
  #   "group.owner": "👑 **Owner**"
  #   "group.admin": "⚔️ **Admin**"
  #   "group.vip": "⭐ **VIP**"
  
  # Using brackets:
  # chat-prefixes:
  #   "group.owner": "[**OWNER**]"
  #   "group.admin": "[**ADMIN**]"
  #   "group.vip": "[**VIP**]"
  
  # Using colors (Discord role colors):
  # chat-prefixes:
  #   "group.owner": "<@&ROLE_ID_HERE>"  # Will show as colored role

# In-game messages
messages:
  # Enable custom in-game messages (requires backend plugin)
  custom-enabled: true
  
  # Message prefix
  prefix: "<gray>[<aqua>VE<gray>]</aqua>"
  
  # Message templates
  no-permission: "{prefix} <red>You don't have permission!"
  sending-to-last-server: "{prefix} <green>Sending you to your last server: <yellow>{server}"
  sending-to-fallback: "{prefix} <yellow>Sending you to the fallback server"
  first-join: "{prefix} <green>Welcome to the network!"

# Debug mode - shows extra logging
debug: false