# ValeStats Configuration

[database]
# PostgreSQL connection settings
host = "valestats-postgres"  # Use container name if using Docker
port = 5432
name = "valestats"
user = "valestats"
password = "changeme"  # CHANGE THIS!

[stats]
# How often to check for stat updates (not used by Velocity, only by processor)
update_interval = 300  # seconds